deploy: improve debugging logs in deploy script
Not sure why in the current deployment we get an error on the Atlan
docs:

```
* API atlan
./.github/scripts/deploy-all.sh: line 44: !tokenKey: unbound variable
Error: Process completed with exit code 1.
```

No idea why because we have a secret variable `ATLEN_BUMP_TOKEN` in
the repo settings 🤷